[package]
name = "antlr4rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
criterion = "*"
lazy_static = "*"

[[bench]]
name = "antlr4rs_benchmark"
harness = false