[package]
name = "antlr4rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "^1.4"

[dev-dependencies]
criterion = "^0.5"

[[bench]]
name = "input_stream_bench"
harness = false